[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
logos.workspace = true
nom = "7.1.3"
pyo3.workspace = true
pythonize.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
