[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
logos.workspace = true
nom = "7.1.3"
pyo3.workspace = true
pythonize.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
