[package]
name = "testing"
version.workspace = true
edition.workspace = true

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
backend = { path = "../backend" }
tracing.workspace = true
tracing-subscriber.workspace = true